# Full configuration reference available at:
# https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/reference.html
dh_auditor:
    enabled: true
    timezone: 'Asia/Kolkata'
    providers:
        doctrine:
            table_prefix: null
            table_suffix: '_audit'
            entities:
                App\Entity\Category:
                    ignored_columns:
                        - createdAt
                        - updatedAt

                App\Entity\Product:
                    ignored_columns:
                        - createdAt
                        - updatedAt

                App\Entity\Site:
                    ignored_columns:
                        - createdAt
                        - updatedAt

                App\Entity\StockRequest:
                    ignored_columns:
                        - createdAt
                        - updatedAt

                App\Entity\StockRequestItem:
                    ignored_columns:
                        - createdAt
                        - updatedAt

                App\Entity\User:
                    ignored_columns:
                        - createdAt
                        - updatedAt

                App\Entity\Inventory:
                    ignored_columns:
                        - createdAt
                        - updatedAt

                App\Entity\StockMovement:
                    ignored_columns:
                        - createdAt
                        - updatedAt

                App\Entity\StockMovementItem:
                    ignored_columns:
                        - createdAt
                        - updatedAt

                App\Entity\ActiveInventory:
                    ignored_columns:
                        - createdAt
                        - updatedAt

                App\Entity\RetiredInventory:
                    ignored_columns:
                        - createdAt