framework:
    workflows:
        stock_request_approval:
            type: 'state_machine'
            supports:
                - App\Entity\StockRequest
            initial_marking: draft
            marking_store:
                type: 'method'
                property: 'status'
            places:
                - draft
                - submitted
                - approved_by_employee
                - approved_by_manager
                - approved
                - rejected
            transitions:
                submit:
                    from: draft
                    to: submitted
                    guard: "is_granted('ROLE_SITE_EMPLOYEE')"

                approve_by_employee:
                    from: submitted
                    to: approved_by_employee
                    guard: "is_granted('ROLE_HQ_EMPLOYEE')"

                approve_by_manager:
                    from: approved_by_employee
                    to: approved_by_manager
                    guard: "is_granted('ROLE_HQ_MANAGER')"

                approve_by_admin:
                    from: approved_by_manager
                    to: approved
                    guard: "is_granted('ROLE_ADMIN')"

                reject:
                    from:
                        - submitted
                        - approved_by_employee
                        - approved_by_manager
                    to: rejected
